- hosts: localhost
  tasks:
  - name: Installing Docker-py For Ansible
    block:
     - command: pip3 show docker-py

    rescue:
     - pip:
        name: docker-py
  - name: Starting docker
    block:
     - service:
         name: docker
         state: started
         enabled: yes
    rescue:
     - debug:
         msg: 'Docker service start' 

  - name: Stoping SELINUX
    ansible.posix.selinux:
       policy: targeted
       state:  permissive
  - name: Launching A Docker Container
    community.general.docker_container:
       name: "aditya"
       image: adity12/ssh:latest
       state: started
       interactive: yes
       detach: yes
       tty: yes
       ports:
               - "8091:80"
 
  - name: Retrieving Docker Container IP
    community.general.docker_container_info:
      name: aditya
    register: x

  - debug:
      var: x.container.NetworkSettings.IPAddress

  - name: Updating Inventory File By Docker Container IP
    blockinfile:
            dest: "/ip.txt"
            block: |
                    [docker]
                    {{ x['container']['NetworkSettings']['IPAddress'] }} ansible_user=test ansible_ssh_pass=aditya ansible_connection=ssh
